version: '2.1'
services:
  mysql-db:
    image: mysql
    container_name: bounty-hunter-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bountyhunterDB
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - bounty-hunter-net
  backend:
    image: backend
    container_name: bounty-hunter-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - bounty-hunter-net

networks:
  bounty-hunter-net:
